sudo: required

services:
  - docker

env:
  global:
    - NODE_ENV=test

script:
  - docker-compose build --no-cache --force-rm
  - docker-compose run web npm test
  - docker-compose stop
  - docker-compose rm -f
